/** Textos de instalaciones (BF-17). */
export const TEXTOS_INSTALACIONES = {
  titulo: "Instalaciones",
  grupos: { ANTES: "Antes", DURANTE: "Durante", DESPUES: "Después" },
  estadosGarantia: { VIGENTE: "Vigente", POR_VENCER: "Por vencer", VENCIDA: "Vencida" } as Record<
    string,
    string
  >,
  nueva: {
    titulo: "Nueva instalación",
    verInstalaciones: "Ver instalaciones",
    encabezado: (fecha: string, usuario: string) => `${fecha} · ${usuario}`,
    consecutivo: "El consecutivo se asigna al guardar.",
    seccionCliente: "Cliente y trabajo",
    direccion: "Dirección de la instalación",
    direccionAyuda: "Se propone la del cliente; se puede cambiar.",
    fecha: "Fecha",
    fechaAyuda: "Puede ser anterior a hoy. Las tasas y las garantías se toman de esa fecha.",
    tecnicos: "Técnicos",
    descripcion: "Descripción del trabajo",
    seccionMaterial: "Material usado",
    sinLineas: "Agrega el material usado. Si solo hubo mano de obra, déjalo vacío.",
    seccionFotos: "Fotos",
    fotosAyuda: "Se suben al guardar la instalación. Se comprimen para no ocupar demasiado espacio.",
    seccionGarantia: "Garantía",
    manoObraMeses: "Garantía de mano de obra",
    meses: (n: number) => (n === 1 ? "1 mes" : `${String(n)} meses`),
    venceManoObra: (fecha: string) => `Mano de obra vigente hasta ${fecha}`,
    venceEquipos: (fecha: string) => `Equipos: 3 meses, hasta ${fecha}`,
    garantiaNota: "Máximo 3 meses desde la fecha de la instalación.",
    condiciones: "Condiciones de la garantía",
    cobro: "Cobro",
    cobroDe: (cliente: string) => `Cobro · ${cliente}`,
    moneda: "Moneda del cobro",
    tasas: (texto: string) => `${texto} · quedan guardadas con la instalación`,
    manoDeObra: "Mano de obra",
    guardar: "Guardar instalación",
    nota: "Se descuenta del inventario · guarda las tasas de la fecha",
  },
  fotos: {
    tomar: (grupo: string) => `Tomar foto · ${grupo}`,
    elegir: (grupo: string) => `Agregar fotos · ${grupo}`,
    contador: (grupo: string, n: number) => `${grupo} · ${String(n)}`,
    quitar: (grupo: string, n: number) => `Quitar foto ${String(n)} de ${grupo}`,
    ver: (grupo: string, n: number) => `Ver foto ${String(n)} de ${grupo}`,
    titulo: (grupo: string, n: number) => `${grupo} · foto ${String(n)}`,
    maximo: (grupo: string) => `${grupo} ya tiene 30 fotos, el máximo.`,
    subiendo: (hecho: number, total: number) => `Subiendo fotos · ${String(hecho)} de ${String(total)}`,
    subidas: (n: number) => (n === 1 ? "1 foto subida." : `${String(n)} fotos subidas.`),
    fallidas: (n: number) =>
      n === 1
        ? "1 foto no se pudo subir. Agrégala de nuevo desde el detalle de la instalación."
        : `${String(n)} fotos no se pudieron subir. Agrégalas de nuevo desde el detalle de la instalación.`,
    quitada: "Foto quitada",
    agregadas: (n: number) => (n === 1 ? "Foto agregada" : `${String(n)} fotos agregadas`),
  },
  confirmacion: {
    titulo: (consecutivo: string) => `Instalación ${consecutivo} registrada`,
    texto: (cliente: string) =>
      `${cliente} · inventario y seriales actualizados. Si hay un error, se corrige anulándola.`,
    garantia: (fecha: string) => `Garantía de mano de obra hasta ${fecha}`,
    ver: "Ver la instalación",
    otra: "Registrar otra instalación",
  },
  listado: {
    nueva: "Nueva instalación",
    garantias: "Garantías",
    tecnico: "Técnico",
    todosTecnicos: "Todos los técnicos",
    estadoGarantia: "Garantía",
    todas: "Todas",
    desde: "Desde",
    hasta: "Hasta",
    incluirAnuladas: "Incluir anuladas",
    totales: "Totales del período",
    periodo: (desde: string, hasta: string) => `Del ${desde} al ${hasta}`,
    instalaciones: (n: number) => (n === 1 ? "1 instalación" : `${String(n)} instalaciones`),
    totalUsd: "Total en USD",
    utilidadUsd: "Utilidad en USD",
    nota: "Sin las instalaciones anuladas.",
    lista: "Instalaciones del período",
    vacio: "No hay instalaciones con estos filtros.",
    anulada: "Anulada",
    utilidad: (valor: string) => `Utilidad ${valor}`,
  },
  detalle: {
    volver: "Instalaciones",
    titulo: (consecutivo: string) => `Instalación ${consecutivo}`,
    cliente: "Cliente",
    documento: "Documento",
    direccion: "Dirección",
    tecnicos: "Técnicos",
    moneda: "Moneda",
    tasas: "Tasas guardadas",
    registrada: "Registrada por",
    cotizacion: "Cotización",
    descripcion: "Descripción del trabajo",
    material: "Material",
    sinMaterial: "Sin material: solo mano de obra.",
    columnas: {
      producto: "Producto",
      cantidad: "Cantidad",
      precio: "Precio unitario",
      subtotal: "Subtotal",
      costo: "Costo USD",
    },
    sugerido: (valor: string) => `Sugerido ${valor}`,
    resumen: "Cobro",
    costoMaterial: "Costo del material (guardado al instalar)",
    descuentoPorcentaje: (valor: string) => `Descuento (${valor} %)`,
    garantias: "Garantías",
    manoObra: (meses: number, fecha: string) =>
      `Mano de obra (${meses === 1 ? "1 mes" : `${String(meses)} meses`}) · hasta ${fecha}`,
    equipos: (fecha: string) => `Equipos · hasta ${fecha}`,
    condiciones: "Condiciones",
    fotos: "Fotos",
    anuladaTitulo: "Instalación anulada",
    anuladaDetalle: (usuario: string, fecha: string) => `Por ${usuario} el ${fecha}`,
    editar: "Datos descriptivos",
    editarNota:
      "La fecha, el plazo de garantía y los valores no se editan: para cambiarlos, se anula y se registra de nuevo.",
    guardar: "Guardar cambios",
    guardado: "Cambios guardados",
    anular: "Anular",
    anularTitulo: (consecutivo: string) => `¿Anular la instalación ${consecutivo}?`,
    anularTexto:
      "El material vuelve a bodega al costo vigente y los seriales quedan disponibles, sin garantía. Las fotos se conservan. No se puede deshacer.",
    motivo: "Motivo de la anulación",
    motivoRequerido: "Escribe el motivo.",
    anulada: (consecutivo: string) => `Instalación ${consecutivo} anulada`,
  },
  validacion: {
    direccion: "Escribe la dirección de la instalación.",
    fecha: "Escribe la fecha.",
    fechaFutura: "La fecha no puede ser posterior a hoy.",
    tecnicos: "Elige al menos un técnico.",
    descripcion: "Escribe la descripción del trabajo.",
    manoDeObra: "Escribe un valor de 0 o más.",
    vacia: "Agrega material o escribe la mano de obra.",
  },
} as const;
