/** Textos de ventas (BF-17). */
export const TEXTOS_VENTAS = {
  titulo: "Ventas",
  nueva: {
    titulo: "Nueva venta",
    verVentas: "Ver ventas",
    encabezado: (fecha: string, usuario: string) => `${fecha} · ${usuario} · de contado`,
    consecutivo: "El consecutivo se asigna al guardar.",
    seccionCliente: "Cliente y moneda",
    moneda: "Moneda de la venta",
    tasas: (texto: string) => `${texto} · quedan guardadas con la venta`,
    trm: (valor: string) => `TRM ${valor}`,
    bolivar: (valor: string) => `Bs ${valor}`,
    seccionProductos: "Productos",
    sinLineas: "Agrega los productos que se venden.",
    sinCliente: "Elige el cliente para ver los precios.",
    etiquetaCantidad: "Cantidad",
    cantidad: (producto: string) => `Cantidad de ${producto}`,
    etiquetaPrecio: "Precio unitario",
    precio: (producto: string) => `Precio unitario de ${producto}`,
    precioAyuda: (sugerido: string) => `Sugerido: ${sugerido}`,
    quitar: (producto: string) => `Quitar ${producto}`,
    disponible: (cantidad: string) => `hay ${cantidad}`,
    costo: "Costo",
    costoHoy: (valor: string) => `Hoy ${valor}`,
    costoCompra: (valor: string, compra: string) => `A tasa de compra ${valor} (${compra})`,
    eligeSeriales: "Elige los seriales que salen.",
    monedaCambiada: "Cambió la moneda: los precios escritos a mano volvieron al sugerido.",
    resumen: "Resumen",
    resumenDe: (cliente: string) => `Resumen · ${cliente}`,
    subtotal: "Subtotal",
    descuento: "Descuento",
    descuentoValor: "Valor del descuento",
    descuentos: { NINGUNO: "Sin descuento", PORCENTAJE: "%", VALOR: "Valor" },
    total: "Total de contado",
    costoMaterial: "Costo vigente del material",
    utilidad: "Utilidad",
    sinStock: "No se puede guardar: hay productos sin stock suficiente.",
    comprobante: "Mostrar el total del comprobante también en",
    observaciones: "Observaciones",
    guardar: "Guardar venta",
    nota: "Se descuenta del inventario · guarda las tasas del día",
  },
  confirmacion: {
    titulo: (consecutivo: string) => `Venta ${consecutivo} registrada`,
    texto: (cliente: string) =>
      `${cliente} · inventario y seriales actualizados. Si hay un error, se corrige anulándola.`,
    ver: "Ver la venta",
    otra: "Registrar otra venta",
  },
  listado: {
    nueva: "Nueva venta",
    cliente: "Cliente",
    producto: "Producto",
    quitarFiltro: (nombre: string) => `${nombre}. Quitar filtro`,
    desde: "Desde",
    hasta: "Hasta",
    incluirAnuladas: "Incluir anuladas",
    totales: "Totales del período",
    periodo: (desde: string, hasta: string) => `Del ${desde} al ${hasta}`,
    ventas: (n: number) => (n === 1 ? "1 venta" : `${String(n)} ventas`),
    totalUsd: "Total en USD",
    utilidadUsd: "Utilidad en USD",
    nota: "Sin las ventas anuladas.",
    lista: "Ventas del período",
    vacio: "No hay ventas en este período.",
    anulada: "Anulada",
    utilidad: (valor: string) => `Utilidad ${valor}`,
  },
  detalle: {
    volver: "Ventas",
    titulo: (consecutivo: string) => `Venta ${consecutivo}`,
    cliente: "Cliente",
    documento: "Documento",
    telefono: "Teléfono",
    direccion: "Dirección",
    moneda: "Moneda",
    tasas: "Tasas guardadas",
    registrada: "Registrada por",
    cotizacion: "Cotización",
    productos: "Productos",
    columnas: {
      producto: "Producto",
      cantidad: "Cantidad",
      precio: "Precio unitario",
      subtotal: "Subtotal",
      costo: "Costo USD",
    },
    sugerido: (valor: string) => `Sugerido ${valor}`,
    garantia: (fecha: string) => `garantía hasta ${fecha}`,
    resumen: "Resumen",
    descuentoPorcentaje: (valor: string) => `Descuento (${valor} %)`,
    anuladaTitulo: "Venta anulada",
    anuladaDetalle: (usuario: string, fecha: string) => `Por ${usuario} el ${fecha}`,
    editar: "Comprobante y observaciones",
    guardar: "Guardar cambios",
    guardado: "Cambios guardados",
    anular: "Anular",
    anularTitulo: (consecutivo: string) => `¿Anular la venta ${consecutivo}?`,
    anularTexto:
      "El material vuelve a bodega al costo vigente y los seriales quedan disponibles, sin garantía. No se puede deshacer.",
    motivo: "Motivo de la anulación",
    motivoRequerido: "Escribe el motivo.",
    anulada: (consecutivo: string) => `Venta ${consecutivo} anulada`,
  },
  validacion: {
    cliente: "Elige el cliente.",
    lineas: "Agrega al menos un producto.",
    cantidad: "Escribe la cantidad.",
    mayorQueCero: "Debe ser mayor que 0.",
    precio: "Escribe un precio de 0 o más.",
    seriales: "Elige los seriales que salen.",
    descuento: "Escribe el descuento.",
    porcentaje: "El porcentaje va de 0 a 100.",
    largo: (n: number) => `Máximo ${String(n)} caracteres.`,
  },
} as const;
