/** Textos comunes a ventas, instalaciones y cotizaciones (BF-17). */
export const TEXTOS_COMERCIAL = {
  cliente: {
    etiqueta: "Cliente",
    elegir: "Elegir cliente",
    cambiar: "Cambiar",
    titulo: "Elegir cliente",
    buscar: "Buscar por nombre, documento o teléfono",
    resultados: "Clientes",
    vacio: "No hay clientes con esa búsqueda.",
    nuevo: "Nuevo cliente",
    tituloNuevo: "Nuevo cliente",
    creado: "Cliente creado",
    quitarFiltro: (nombre: string) => `Cliente: ${nombre}. Quitar filtro`,
  },
  seriales: {
    titulo: "Seriales que salen",
    elegidos: (n: number) => (n === 1 ? "1 elegido" : `${String(n)} elegidos`),
    vacio: "No hay seriales en bodega.",
    noEnBodega: (serial: string) => `${serial} no está en bodega para este producto.`,
    elegido: (serial: string) => `${serial} elegido`,
    serial: (numero: string) => `Serial ${numero}`,
  },
  material: {
    etiquetaCantidad: "Cantidad",
    cantidad: (producto: string) => `Cantidad de ${producto}`,
    etiquetaPrecio: "Precio unitario",
    precio: (producto: string) => `Precio unitario de ${producto}`,
    precioAyuda: (sugerido: string) => `Sugerido: ${sugerido}`,
    quitar: (producto: string) => `Quitar ${producto}`,
    disponible: (cantidad: string) => `hay ${cantidad}`,
    costo: "Costo",
    costoHoy: (valor: string) => `Hoy ${valor}`,
    costoCompra: (valor: string, compra: string) => `A tasa de compra ${valor} (${compra})`,
    monedaCambiada: "Cambió la moneda: los precios escritos a mano volvieron al sugerido.",
    sinCliente: "Elige el cliente para ver los precios.",
  },
  cobro: {
    material: "Material",
    manoDeObra: "Mano de obra",
    subtotal: "Subtotal",
    descuento: "Descuento",
    descuentoValor: "Valor del descuento",
    descuentos: { NINGUNO: "Sin descuento", PORCENTAJE: "%", VALOR: "Valor" },
    total: "Total de contado",
    costoMaterial: "Costo vigente del material",
    utilidad: "Utilidad",
    sinStock: "No se puede guardar: hay productos sin stock suficiente.",
    comprobante: "Mostrar el total del comprobante también en",
    observaciones: "Observaciones",
  },
  validacion: {
    cliente: "Elige el cliente.",
    lineas: "Agrega al menos un producto.",
    cantidad: "Escribe la cantidad.",
    mayorQueCero: "Debe ser mayor que 0.",
    seriales: "Elige los seriales que salen.",
    descuento: "Escribe el descuento.",
    porcentaje: "El porcentaje va de 0 a 100.",
    largo: (n: number) => `Máximo ${String(n)} caracteres.`,
  },
  comprobante: {
    descargar: "Descargar PDF",
    whatsapp: "Enviar por WhatsApp",
    whatsappLargo: "Enviar comprobante por WhatsApp",
    compartirTitulo: (consecutivo: string) => `Comprobante ${consecutivo}`,
  },
} as const;
