/** Textos de clientes (BF-17). */
export const TEXTOS_CLIENTES = {
  titulo: "Clientes",
  subtitulo: "El tipo de cliente define el precio que se aplica",
  nuevo: "Nuevo cliente",
  buscar: "Buscar por nombre, documento, teléfono o ciudad",
  filtroTipo: "Tipo de cliente",
  tipos: { todos: "Todos", INSTALADOR: "Instalador", CLIENTE_FINAL: "Cliente final" },
  tiposPlural: { todos: "Todos", INSTALADOR: "Instaladores", CLIENTE_FINAL: "Clientes finales" },
  vacio: "No hay clientes con estos filtros.",
  vacioSinFiltros: "Todavía no hay clientes. Crea el primero.",
  movimientos: (n: number) => (n === 1 ? "1 movimiento" : `${String(n)} movimientos`),
  ultimo: (fecha: string) => `último ${fecha}`,
  sinMovimientos: "Sin movimientos",
  precioAplicado: {
    INSTALADOR: "Se le aplicará el precio instalador",
    CLIENTE_FINAL: "Se le aplicará el precio cliente final",
  },
  formulario: {
    tituloNuevo: "Nuevo cliente",
    tituloEditar: "Editar cliente",
    tipo: "Tipo de cliente",
    nombre: "Nombre o razón social",
    tipoDocumento: "Tipo de documento",
    sinDocumento: "Sin documento",
    numeroDocumento: "Número de documento",
    telefono: "Teléfono / WhatsApp",
    telefonoAyuda: "Si lo escribes sin indicativo, se asume +57 (Colombia). Para Venezuela, empieza con +58.",
    correo: "Correo",
    direccion: "Dirección",
    direccionAyuda: "Se propone como dirección de las instalaciones.",
    ciudad: "Ciudad",
    guardar: "Guardar",
    creado: "Cliente creado",
    guardado: "Cliente guardado",
  },
  detalle: {
    whatsapp: "WhatsApp",
    venta: "Venta",
    instalacion: "Instalación",
    cotizacion: "Cotización",
    editar: "Editar",
    precio: "Precio que se aplica",
    compras: "Compras de material",
    instalaciones: "Instalaciones",
    historial: "Historial",
    sinHistorial: "Este cliente todavía no tiene ventas ni instalaciones.",
    anulada: "Anulada",
    tiposDocumento: { VENTA: "Venta", INSTALACION: "Instalación" } as Record<string, string>,
  },
  validacion: {
    nombre: "Escribe el nombre o la razón social.",
    telefono: "Escribe el teléfono o WhatsApp.",
    documento: "Solo números, puntos y guion.",
    correo: "Escribe un correo válido.",
    largo: (n: number) => `Máximo ${String(n)} caracteres.`,
  },
} as const;
