/** Textos de configuración (BF-17). */
export const TEXTOS_CONFIGURACION = {
  titulo: "Configuración",
  subtitulo: "Datos de la empresa para los PDF, valores por defecto, categorías y unidades de medida.",
  pestanas: {
    empresa: "Empresa",
    valores: "Valores por defecto",
    categorias: "Categorías",
    unidades: "Unidades de medida",
    carga: "Carga inicial",
  },
  carga: {
    paso1: "Descarga la plantilla",
    paso1Texto:
      "Trae las hojas Productos, Inventario inicial, Clientes y Proveedores. Los ejemplos están en la hoja Instrucciones.",
    descargar: "Descargar plantilla",
    nombrePlantilla: "plantilla-carga-inicial.xlsx",
    paso2: "Sube el archivo lleno",
    paso2Texto: "Se revisa todo antes de guardar: si hay errores, no se guarda nada.",
    archivo: "Archivo de Excel (.xlsx)",
    elegir: "Elegir archivo",
    soloXlsx: "Elige un archivo de Excel (.xlsx).",
    tamano: "El archivo pesa más de 5 MB.",
    validando: "Revisando el archivo…",
    conErrores: (n: number) =>
      n === 1
        ? "El archivo tiene 1 error. Corrígelo y vuelve a subirlo."
        : `El archivo tiene ${String(n)} errores. Corrígelos y vuelve a subirlo.`,
    erroresDe: (hoja: string) => `Hoja ${hoja}`,
    fila: (n: number) => `Fila ${String(n)}`,
    valido: "El archivo está listo para cargar.",
    resumen: "Se va a crear",
    productos: "Productos",
    clientes: "Clientes",
    proveedores: "Proveedores",
    productosConStock: "Productos con stock",
    valor: "Valor del inventario",
    paso3: "Confirma la carga",
    confirmar: "Confirmar la carga",
    registrada: (consecutivo: string) => `Carga ${consecutivo} registrada`,
    realizadas: "Cargas realizadas",
    sinCargas: "Todavía no se ha hecho ninguna carga.",
    columnas: {
      consecutivo: "Documento",
      fecha: "Fecha",
      usuario: "Usuario",
      archivo: "Archivo",
      totales: "Creados",
      valor: "Valor (USD)",
    },
    totales: (p: number, c: number, pr: number) =>
      `${String(p)} productos · ${String(c)} clientes · ${String(pr)} proveedores`,
  },
  empresa: {
    nombre: "Nombre de la empresa",
    lema: "Lema",
    nit: "NIT",
    ciudad: "Ciudad",
    telefono: "Teléfono",
    correo: "Correo",
    logo: "Logo para los PDF",
  },
  valores: {
    validez: "Validez de las cotizaciones",
    garantiaManoObra: "Garantía de mano de obra",
    garantiaEquipos: "Garantía de equipos",
    limite: "Límite de variación de tasas (%)",
    limiteAyuda: "Si una tasa manual cambia más que esto, se pide confirmarla (RF-35).",
    condiciones: "Condiciones de garantía",
    pie: "Pie de los PDF",
    dias: (n: number) => `${String(n)} días`,
    meses: (n: number) => (n === 1 ? "1 mes" : `${String(n)} meses`),
  },
  guardar: "Guardar cambios",
  guardado: "Configuración guardada",
  validacion: {
    nombre: "Escribe el nombre de la empresa.",
    largo: (n: number) => `Máximo ${String(n)} caracteres.`,
    correo: "Escribe un correo válido.",
    limite: "Escribe el límite de variación.",
    limiteRango: "El límite debe ser mayor que 0 y máximo 100.",
    condiciones: "Escribe las condiciones de garantía.",
    pie: "Escribe el pie de los PDF.",
  },
  categorias: {
    nueva: "Nueva categoría",
    renombrar: "Renombrar",
    eliminar: "Eliminar",
    nombre: "Nombre de la categoría",
    productos: (n: number) => (n === 1 ? "1 producto" : `${String(n)} productos`),
    vacio: "No hay categorías.",
    tituloNueva: "Nueva categoría",
    tituloEditar: "Renombrar categoría",
    confirmarEliminar: (nombre: string) => `¿Eliminar la categoría «${nombre}»?`,
    soloSinProductos: "Solo se pueden eliminar las categorías sin productos.",
    creada: "Categoría creada",
    actualizada: "Categoría actualizada",
    eliminada: "Categoría eliminada",
    requerido: "Escribe el nombre de la categoría.",
  },
  unidades: {
    nueva: "Nueva unidad",
    editar: "Editar",
    eliminar: "Eliminar",
    nombre: "Nombre",
    abreviatura: "Abreviatura",
    admiteDecimales: "Admite cantidades con decimales (hasta 2, por ejemplo 12,5 m)",
    conDecimales: "Admite decimales",
    soloEnteras: "Solo cantidades enteras",
    vacio: "No hay unidades de medida.",
    tituloNueva: "Nueva unidad de medida",
    tituloEditar: "Editar unidad de medida",
    confirmarEliminar: (nombre: string) => `¿Eliminar la unidad «${nombre}»?`,
    soloSinUso: "Solo se pueden eliminar las unidades que ningún producto usa.",
    creada: "Unidad creada",
    actualizada: "Unidad actualizada",
    eliminada: "Unidad eliminada",
    requeridoNombre: "Escribe el nombre de la unidad.",
    requeridoAbreviatura: "Escribe la abreviatura.",
  },
  cancelar: "Cancelar",
  guardarDialogo: "Guardar",
} as const;
