/** Textos de tasas de cambio (BF-17). */
export const TEXTOS_TASAS = {
  titulo: "Tasas de cambio",
  subtitulo: "USD es la moneda principal. Cada documento guarda las tasas con las que se registró.",
  recuadro: "Tasas de hoy · 1 USD",
  trm: "USD / COP · TRM",
  bolivar: "USD / VES · ingreso manual",
  fuente: { SUPERFINANCIERA: "Superintendencia Financiera", MANUAL: "Manual" },
  sinTasa: "Sin registrar",
  registrarVes: "Registrar tasa del día",
  corregirVesHoy: "Corregir tasa de hoy",
  ingresarTrm: "Ingresar TRM manual",
  reintentarTrm: "Reintentar consulta",
  reglas: (limite: string) => `Doble digitación y alerta si varía más del ${limite} % (configurable).`,
  historial: "Historial diario",
  desde: "Desde",
  hasta: "Hasta",
  sinHistorial: "No hay tasas registradas en estas fechas.",
  limiteHistorial: "Se muestran los 100 días más recientes del rango.",
  corregir: "Corregir",
  correcciones: "Correcciones de tasas",
  correccionesNota: "Los documentos ya guardados conservan la tasa con la que se registraron.",
  sinCorrecciones: "No hay correcciones en estas fechas.",
  correccionesParciales: (dias: number) =>
    `Se muestran las correcciones de los ${String(dias)} días más recientes del rango.`,
  trmOficial: "TRM oficial (automática)",
  consulta: {
    EXITO: "Se obtuvo la TRM oficial de hoy.",
    OMITIDA: "La TRM de hoy ya estaba registrada.",
    FALLO: "La consulta volvió a fallar. Puedes ingresar la TRM manualmente.",
  },
  dialogo: {
    tituloVes: "Tasa del bolívar de hoy",
    tituloTrm: "TRM manual de hoy",
    tituloCorregir: (par: string, fecha: string) => `Corregir ${par} del ${fecha}`,
    unidadVes: "Bolívares por 1 USD",
    unidadTrm: "Pesos por 1 USD",
    tasa: "Tasa",
    repite: "Repite la tasa",
    ayudaFormato: "Usa coma o punto para los decimales, sin separador de miles.",
    seGuardara: (valor: string) => `Se guardará: ${valor}`,
    noCoinciden: "Los dos valores no coinciden. Digítala de nuevo.",
    requerido: "Escribe la tasa.",
    mayorQueCero: "La tasa debe ser mayor que 0.",
    anterior: "Anterior",
    nueva: "Nueva",
    variacion: "Variación",
    sinAnterior: "No hay una tasa anterior para comparar.",
    alertaVariacion: (porcentaje: string, limite: string) =>
      `La tasa cambia ${porcentaje} %, más que el límite de ${limite} %. Revisa que esté bien digitada.`,
    aceptar: (porcentaje: string) => `Confirmo la variación de ${porcentaje} %`,
    motivo: "Motivo de la corrección (opcional)",
    guardar: "Guardar tasa",
    cancelar: "Cancelar",
    registrada: "Tasa registrada",
    corregida: "Tasa corregida",
    yaRegistrada: "Ya hay una tasa del bolívar registrada hoy. Si está mal, corrígela.",
  },
} as const;

export const NOMBRE_PAR = { USD_COP: "USD/COP", USD_VES: "USD/VES" } as const;
