/** Textos de inventario y productos (BF-17). */
export const TEXTOS_PRODUCTOS = {
  titulo: "Inventario",
  resumen: (n: number) => (n === 1 ? "1 producto" : `${String(n)} productos`),
  nuevo: "Nuevo producto",
  buscar: "Buscar por nombre, código o marca",
  todas: "Todas",
  filtroCategoria: "Categoría",
  estado: "Estado",
  estados: { activos: "Activos", inactivos: "Inactivos", todos: "Todos" },
  vacio: "No hay productos con estos filtros.",
  vacioSinFiltros: "Todavía no hay productos. Crea el primero.",
  conSerial: "Con serial",
  sinSerial: "Sin serial",
  stock: "Stock",
  bajo: "Bajo",
  inactivo: "Inactivo",
  instalador: "Instalador",
  clienteFinal: "Cliente final",
  formulario: {
    tituloNuevo: "Nuevo producto",
    tituloEditar: "Editar producto",
    volver: "Inventario",
    codigo: "Código",
    codigoAyuda: "Único. Por ejemplo CAM-D2. Se guarda en mayúsculas.",
    nombre: "Nombre",
    marca: "Marca",
    modelo: "Modelo",
    categoria: "Categoría",
    elegir: "Elige…",
    unidad: "Unidad de medida",
    controlaSerial: "Controla serial (equipos con número de serie de fábrica)",
    bloqueoMovimientos:
      "Si el producto ya tiene movimientos, la unidad y el control de serial no se pueden cambiar.",
    monedaPrecio: "Moneda de los precios",
    precioInstalador: "Precio instalador",
    precioClienteFinal: "Precio cliente final",
    stockMinimo: "Stock mínimo",
    stockMinimoAyuda: "Opcional. Por debajo de este valor el producto aparece como Bajo.",
    descripcion: "Descripción",
    soloLectura: "Calculados por el sistema",
    stockActual: "Stock actual",
    costoActual: "Costo actual (USD)",
    sinCosto: "Sin costo todavía: se calcula con la primera compra.",
    foto: "Foto del producto",
    fotoDespues: "Podrás agregar la foto después de crear el producto.",
    guardar: "Guardar",
    creado: "Producto creado",
    creadoDetalle: "Ahora puedes agregar la foto.",
    guardado: "Producto guardado",
    desactivar: "Desactivar",
    activar: "Activar",
    desactivado: "Producto desactivado",
    activado: "Producto activado",
    eliminar: "Eliminar",
    confirmarEliminar: (nombre: string) => `¿Eliminar «${nombre}»?`,
    explicacionEliminar:
      "Solo se puede eliminar si no tiene movimientos. Si ya los tiene, puedes desactivarlo.",
    eliminado: "Producto eliminado",
    inactivoAviso: "Este producto está inactivo: no se ofrece para vender, pero conserva su historial.",
  },
  validacion: {
    codigo: "Escribe el código.",
    codigoFormato: "Solo letras, números, punto, guion, guion bajo y barra.",
    nombre: "Escribe el nombre.",
    categoria: "Elige la categoría.",
    unidad: "Elige la unidad de medida.",
    precio: "Escribe el precio.",
    largo: (n: number) => `Máximo ${String(n)} caracteres.`,
  },
} as const;

export const MONEDAS = [
  { valor: "USD", etiqueta: "USD · dólares" },
  { valor: "COP", etiqueta: "COP · pesos" },
  { valor: "VES", etiqueta: "VES · bolívares" },
] as const;
