/** Textos del inventario de la Fase 2: valorizado, detalle, kárdex, ajustes y seriales (BF-17). */
export const TEXTOS_INVENTARIO = {
  listado: {
    registrarCompra: "Registrar compra",
    ajustes: "Ajustes",
    valorTotal: "Valor del inventario",
    buscar: "Buscar por nombre, código, marca o serial",
    costo: "Costo USD",
    valor: "Valor en bodega",
    vacioSinFiltros: "Todavía no hay productos.",
    cargaInicial: "Cargar el inventario desde Excel",
  },
  detalle: {
    volver: "Inventario",
    editar: "Editar",
    ajustar: "Ajustar inventario",
    unidad: (u: string) => `unidad: ${u}`,
    stock: "Stock actual",
    minimo: (m: string) => `mínimo ${m}`,
    costo: "Costo actual",
    sinCosto: "Sin costo todavía",
    valor: "Valor en bodega",
    precioInstalador: "Precio instalador",
    precioClienteFinal: "Precio cliente final",
    inactivo: "Producto inactivo: no se ofrece para vender.",
    seriales: "Seriales",
    estadosSerial: {
      enBodega: "En bodega",
      vendidos: "Vendidos",
      instalados: "Instalados",
      dadosDeBaja: "Dados de baja",
      anulados: "Anulados",
    },
    verSeriales: "Ver seriales",
    ocultarSeriales: "Ocultar seriales",
    sinSeriales: "No hay seriales.",
    kardex: "Kárdex",
    sinMovimientos: "Este producto todavía no tiene movimientos.",
    columnas: {
      fecha: "Fecha",
      movimiento: "Movimiento",
      documento: "Doc.",
      entrada: "Entrada",
      salida: "Salida",
      saldo: "Saldo",
      usuario: "Usuario",
    },
    historialCosto: "Historial de costo",
    historialCostoNota:
      "Costo en USD. Si la factura sube, todo pasa al precio mayor; si baja o es igual, se promedia.",
    sinCambiosCosto: "El costo todavía no ha cambiado.",
    columnasCosto: {
      fecha: "Fecha",
      documento: "Documento",
      factura: "Costo en la factura",
      tasa: "Tasa",
      anterior: "Anterior",
      nuevo: "Nuevo",
      regla: "Regla",
    },
  },
  reglas: {
    SUBE: "sube",
    PROMEDIO: "promedio",
    SIN_STOCK: "sin stock",
    AJUSTE: "ajuste",
    INVENTARIO_INICIAL: "inventario inicial",
    ANULACION: "anulación",
  } as Record<string, string>,
  estadoSerial: {
    EN_BODEGA: "En bodega",
    VENDIDO: "Vendido",
    INSTALADO: "Instalado",
    DADO_DE_BAJA: "Dado de baja",
    ANULADO: "Anulado",
  } as Record<string, string>,
  selector: {
    agregar: "Agregar producto",
    titulo: "Agregar producto",
    buscar: "Buscar por código o nombre",
    resultados: "Productos",
    vacio: "No hay productos activos con esa búsqueda.",
    conSerial: "con serial",
  },
  serialesBodega: {
    titulo: "Seriales que salen",
    elegidos: (n: number) => (n === 1 ? "1 serial elegido" : `${String(n)} seriales elegidos`),
    vacio: "No hay seriales en bodega.",
  },
  buscarSerial: {
    boton: "Buscar serial",
    titulo: "Buscar un serial",
    campo: "Número de serie",
    buscar: "Buscar",
    vacio: "No se encontró ningún serial con ese número.",
    resultados: "Seriales encontrados",
    minimo: "Escribe al menos 2 caracteres.",
  },
  serial: {
    volver: "Inventario",
    titulo: (numero: string) => `Serial ${numero}`,
    producto: "Producto",
    estado: "Estado",
    entrada: "Entrada",
    salida: "Salida",
    garantia: "Garantía hasta",
    movimientos: "Historial",
    reclamos: "Reclamos",
    sinMovimientos: "Sin movimientos.",
    tipos: {
      ENTRADA: "Entrada",
      BAJA: "Baja",
      ANULACION: "Anulación de la entrada",
      VENTA: "Venta",
      ANULACION_VENTA: "Anulación de la venta",
      INSTALACION: "Instalación",
      ANULACION_INSTALACION: "Anulación de la instalación",
    } as Record<string, string>,
  },
  ajuste: {
    titulo: "Ajustar inventario",
    tipo: "Tipo de ajuste",
    entrada: "Entrada",
    salida: "Salida",
    motivo: "Motivo",
    motivos: {
      PERDIDA: "Pérdida",
      DANO: "Daño",
      CONTEO_FISICO: "Conteo físico",
      GARANTIA: "Garantía",
      OTRO: "Otro",
    },
    descripcion: "Descripción",
    descripcionOtro: "Obligatoria si el motivo es Otro.",
    cantidad: "Cantidad",
    cantidadSeriales: "La cantidad es la de los seriales elegidos.",
    costo: "Costo unitario en USD",
    costoAyuda: "El producto nunca ha tenido costo: este será su costo (P-25).",
    costoVigente: (costo: string) => `Entra al costo vigente (${costo}) y no lo cambia.`,
    nuevoStock: (antes: string, despues: string) => `Stock ${antes} → ${despues}`,
    stockInsuficiente: (quedan: string) => `Stock insuficiente · quedan ${quedan}`,
    noSeAnula:
      "Los ajustes no se editan ni se anulan: un error se corrige con otro ajuste en sentido contrario.",
    guardar: "Guardar ajuste",
    registrado: (consecutivo: string) => `Ajuste ${consecutivo} registrado`,
    validacion: {
      cantidad: "Escribe la cantidad.",
      mayorQueCero: "La cantidad debe ser mayor que 0.",
      descripcion: "Escribe la descripción.",
      costo: "Escribe el costo unitario en USD.",
      seriales: "Escribe un serial por unidad, sin repetir.",
      elegirSeriales: "Elige los seriales que salen.",
      largo: (n: number) => `Máximo ${String(n)} caracteres.`,
    },
  },
  ajustes: {
    titulo: "Ajustes de inventario",
    volver: "Inventario",
    lista: "Ajustes",
    vacio: "No hay ajustes con estos filtros.",
    nota: "Para registrar un ajuste, abre el producto en el inventario y elige Ajustar inventario.",
    quitarProducto: (nombre: string) => `Producto: ${nombre}. Quitar filtro`,
    tipos: { ENTRADA: "Entrada", SALIDA: "Salida" } as Record<string, string>,
    producto: "Producto",
    desde: "Desde",
    hasta: "Hasta",
  },
  detalleAjuste: {
    volver: "Ajustes",
    titulo: (consecutivo: string) => `Ajuste ${consecutivo}`,
    producto: "Producto",
    tipo: "Tipo",
    motivo: "Motivo",
    descripcion: "Descripción",
    cantidad: "Cantidad",
    costo: "Costo unitario (USD)",
    valor: "Valor (USD)",
    seriales: "Seriales",
    registrado: "Registrado por",
  },
} as const;
