/** Textos de compras y proveedores (BF-17). */
export const TEXTOS_COMPRAS = {
  titulo: "Compras",
  pestanas: { compras: "Compras", proveedores: "Proveedores" },
  proveedores: {
    nuevo: "Nuevo proveedor",
    verCompras: "Ver compras",
    buscar: "Buscar por nombre, NIT o ciudad",
    vacio: "No hay proveedores con esta búsqueda.",
    vacioSinFiltros: "Todavía no hay proveedores. Crea el primero.",
    moneda: "Moneda habitual",
    nit: "NIT",
  },
  formulario: {
    tituloNuevo: "Nuevo proveedor",
    tituloEditar: "Editar proveedor",
    volver: "Proveedores",
    nombre: "Nombre o razón social",
    nit: "NIT o documento",
    telefono: "Teléfono",
    correo: "Correo",
    ciudad: "Ciudad",
    moneda: "Moneda habitual",
    monedaAyuda: "Se propone al registrar una compra de este proveedor (RF-40).",
    guardar: "Guardar",
    creado: "Proveedor creado",
    guardado: "Proveedor guardado",
  },
  listado: {
    nueva: "Registrar compra",
    proveedor: "Proveedor",
    todosProveedores: "Todos los proveedores",
    producto: "Producto",
    todosProductos: "Todos los productos",
    desde: "Desde",
    hasta: "Hasta",
    incluirAnuladas: "Incluir anuladas",
    periodo: (desde: string, hasta: string) => `Del ${desde} al ${hasta}`,
    totales: "Totales del período",
    totalesNota: "Sin las compras anuladas.",
    totalUsd: "Total en USD",
    compras: (n: number) => (n === 1 ? "1 compra" : `${String(n)} compras`),
    factura: (n: string) => `Factura ${n}`,
    verFactura: "Ver factura",
    anulada: "Anulada",
    tasa: "Tasa",
    vacio: "No hay compras en este período.",
    lista: "Compras del período",
  },
  nueva: {
    titulo: "Nueva compra",
    volver: "Compras",
    encabezado: (fecha: string, usuario: string) => `${fecha} · ${usuario}`,
    consecutivo: "El consecutivo se asigna al guardar.",
    seccionProveedor: "Proveedor y factura",
    proveedor: "Proveedor",
    elegirProveedor: "Elige el proveedor",
    sueleFacturar: (m: string) => `Suele facturar en ${m}.`,
    numeroFactura: "N.º de factura del proveedor",
    moneda: "Moneda de la factura",
    fecha: "Fecha de la factura",
    fechaAyuda: "Puede ser anterior a hoy, nunca posterior. Define las tasas que se usan (P-19).",
    seccionProductos: "Productos comprados",
    sinLineas: "Agrega los productos de la factura.",
    etiquetaCantidad: "Cantidad",
    etiquetaCosto: "Costo unitario",
    cantidad: (producto: string) => `Cantidad de ${producto}`,
    costo: (producto: string) => `Costo unitario de ${producto}`,
    costoAyuda: (moneda: string, unidad: string) => `${moneda} por ${unidad}`,
    quitar: (producto: string) => `Quitar ${producto}`,
    stockActual: (stock: string) => `Stock actual ${stock}`,
    cambioCosto: (antes: string, despues: string) => `Costo ${antes} → ${despues}`,
    costoNuevo: (despues: string) => `Costo inicial ${despues}`,
    total: "Total de la compra",
    calculando: "Calculando…",
    tasas: "Tasas que se usarán",
    trm: (valor: string, fecha: string) => `TRM ${valor} (${fecha})`,
    bolivar: (valor: string, fecha: string) => `Bolívar ${valor} (${fecha})`,
    sinTasa: "sin tasa",
    factura: "Factura (foto o PDF)",
    facturaAyuda: "Opcional. Hasta 5 MB. Se sube al guardar la compra.",
    quitarFactura: "Quitar el archivo",
    faltanSeriales: (n: number) =>
      n === 1 ? "Faltan seriales en 1 producto." : `Faltan seriales en ${String(n)} productos.`,
    guardar: "Guardar y sumar al inventario",
    noSeEdita: "Una vez guardada no se edita: se anula y se registra de nuevo.",
    registrada: (consecutivo: string) => `Compra ${consecutivo} registrada`,
    facturaNoSubida:
      "La compra quedó guardada, pero la factura no se pudo subir. Vuelve a adjuntarla desde el detalle.",
  },
  detalle: {
    volver: "Compras",
    titulo: (consecutivo: string) => `Compra ${consecutivo}`,
    proveedor: "Proveedor",
    factura: "Factura",
    fecha: "Fecha de la factura",
    moneda: "Moneda",
    tasas: "Tasas guardadas",
    registrada: "Registrada por",
    productos: "Productos",
    columnas: {
      producto: "Producto",
      cantidad: "Cantidad",
      costo: "Costo unitario",
      subtotal: "Subtotal",
      cambio: "Costo USD",
      regla: "Regla",
    },
    seriales: "Seriales",
    total: "Total",
    equivalente: (usd: string) => `Equivale a ${usd}`,
    archivo: "Factura adjunta",
    sinArchivo: "Sin factura adjunta.",
    verArchivo: "Ver factura",
    adjuntar: "Adjuntar factura",
    reemplazar: "Reemplazar",
    quitar: "Quitar",
    quitarTitulo: "¿Quitar la factura adjunta?",
    quitarTexto: "La compra no cambia; solo se quita el archivo.",
    archivoGuardado: "Factura adjuntada",
    archivoQuitado: "Factura quitada",
    anular: "Anular",
    anularTitulo: (consecutivo: string) => `¿Anular la compra ${consecutivo}?`,
    anularTexto:
      "Se restan las unidades del inventario, el costo vuelve al anterior y los seriales quedan anulados. No se puede deshacer.",
    motivo: "Motivo de la anulación",
    motivoRequerido: "Escribe el motivo.",
    anulada: (consecutivo: string) => `Compra ${consecutivo} anulada`,
    noAnulableAyuda: "Para corregirla, registra un ajuste de inventario.",
    anuladaTitulo: "Compra anulada",
    anuladaDetalle: (usuario: string, fecha: string) => `Por ${usuario} el ${fecha}`,
  },
  archivoFactura: {
    tipo: "Elige una imagen (JPEG, PNG o WebP) o un PDF.",
    tamano: "El archivo pesa más de 5 MB.",
  },
  validacion: {
    proveedor: "Elige el proveedor.",
    numeroFactura: "Escribe el número de factura.",
    fecha: "Escribe la fecha de la factura.",
    fechaFutura: "La fecha no puede ser posterior a hoy.",
    lineas: "Agrega al menos un producto.",
    cantidad: "Escribe la cantidad.",
    mayorQueCero: "Debe ser mayor que 0.",
    costo: "Escribe el costo unitario.",
    seriales: "Escribe un serial por unidad, sin repetir.",
    nombre: "Escribe el nombre o la razón social.",
    nit: "Solo números, puntos y guion.",
    correo: "Escribe un correo válido.",
    largo: (n: number) => `Máximo ${String(n)} caracteres.`,
  },
} as const;
